### ISSUE TITLE
Installing in the correct folder ?

### ISSUE THREAD

**Issue by newbie14** [ManuelGil/REST-Api-with-Slim-PHP#1]
I have followed you advice given that is composer require slim/slim "^3.0"
Now when I go it create a folder called vendor and in it is slim with many slims folder like this /var/www/html/vendor/slim/slim/Slim so where to copy your codes ? Please advice ?

**Comment by ManuelGil** [comment]
Hi @newbie14 ,

This is my configuration. I hope you find it useful.

![rest](https://user-images.githubusercontent.com/25472045/36651963-d476e6b4-1a79-11e8-99cb-d3f000712173.PNG)

**Comment by newbie14** [comment]
Hi manuel,
                 Thank you so added on your public and src folder rite ?

**Comment by ManuelGil** [comment]
@newbie14 , you can add the folders in the root and run the web service without problems

**Comment by newbie14** [comment]
@ManuelGil I dont get what you do you mean by adding the folders in root? I need to run different application besides this api ?

**Comment by ManuelGil** [comment]
Hi @newbie14 

I'm sorry to being late.

I updated this project adding features and improving the installation process.

I hope this update solves your doubts.

I remain attentive to your comments.
