### ISSUE TITLE
Update doc with 'login' and 'register' api example to get clear idea

### ISSUE THREAD

**Issue by codefuelIN** [ManuelGil/REST-Api-with-Slim-PHP#2]
Hi,

First of all thank you for creating this clean starter project. I was experimenting with it, I installed and setup as per the instruction.

Currently when I hit an api lets say GET to `http://localhost/REST-api-with-slim-PHP/public/webresources/mobile_app/ping`

It send me response back `pong` which is correct.

But could you provide me example for LOGIN and REGISTER ?

I assume that for LOGIN it would be `http://localhost/REST-api-with-slim-PHP/public/webresources/mobile_app/login/testUser/testPwd`  (without Bearer token)

I am getting blank response for above hit. Could you suggest me where I am doing wrong?

**Comment by ManuelGil** [comment]
Hi @codefuelIN ,

The install  folder contains a batch of DDL statements and a batch of DML statements in a plain text files.

Please, import the batch DML statements to the database for you can register a new user.

The register use this struture: 

> /webresources/mobile_app/register/{username}/{password}/{country_id}

For example, if you want to select the location in the United States, insert the country_id [226](https://github.com/ManuelGil/REST-Api-with-Slim-PHP/blob/master/install/NETWORK%20SCHEMA%20DML.sql#L244):

![image](https://user-images.githubusercontent.com/25472045/38226777-e255805c-36c0-11e8-997e-b0c7311cfda7.png)

I hope that it helps you.

Thanks for your comments.
