### ISSUE TITLE
Keep getting 401 unauthorized

### ISSUE THREAD

**Issue by luxorweb** [ManuelGil/REST-Api-with-Slim-PHP#4]
Hi Manuel thanks for this API,
i succeded in installing and making calls but I keep getting a 401 error when I try methods that need the autentication token. Here's the screen...

![issue_401](https://user-images.githubusercontent.com/10399799/41282105-8a848418-6e33-11e8-99b9-b4f163c0048f.png)

I enabled displayErrorDetails in the index, how can I debug this?

**Comment by ManuelGil** [comment]
Hi @luxorweb 

Please go to https://jwt.io/ and check your token. The token may not be encoded correctly.

![image](https://user-images.githubusercontent.com/25472045/41330671-754c1856-6e9a-11e8-8cb5-bd4ddc638871.png)

I stay for your reply.

**Comment by luxorweb** [comment]
Hi, it seems the token is ok...
![screenshot-2018-6-13 jwt io](https://user-images.githubusercontent.com/10399799/41339394-009f5832-6ef5-11e8-8ed7-78fb01d80600.png)

Is there any debug configuration to enable so I can give further info?

**Comment by ManuelGil** [comment]
@luxorweb , please, replace "$app = new \Slim\App;" in line [5](https://github.com/ManuelGil/REST-Api-with-Slim-PHP/blob/master/public/index.php#L5) of the index.php for:

```PHP
$config = [
    'settings' => [
        'displayErrorDetails' => true,
    ],
];

$app = new \Slim\App($config);
```
This is a displayErrorDetails  of Slim Framework.

Please reply a new response.

Thanks.

**Comment by luxorweb** [comment]
@ManuelGil 
I did it before writing... unfortunately no error comes up, just header 401...
Maybe a debug in the jwt module?

**Comment by ManuelGil** [comment]
@luxorweb 
The JWT Module of Tuupola has [this instruction](https://github.com/tuupola/slim-jwt-auth#error) into the documentation. Try include the error function after of secret in the [api file](https://github.com/ManuelGil/REST-Api-with-Slim-PHP/blob/master/src/routes/api.php#L25).
