### ISSUE TITLE
Could you create the unit test for these apis?

### ISSUE THREAD

**Issue by DonnieCha** [ManuelGil/REST-Api-with-Slim-PHP#5]
Hi.

Thanks for the these API. It's pretty code.
Btw, i want to know how to create unit test for it.
Could you create the unit test for these apis?

Thanks again.

**Comment by ManuelGil** [comment]
Hi Donnie,

I has been working in these, but I can't construct a unit test without make big changes in the actual structure.

I include same routes in [`api.php`](https://github.com/ManuelGil/REST-Api-with-Slim-PHP/blob/master/src/routes/api.php#L375) for the unit test waiting for the help for this process.

I hope you have a great day.

**Comment by ManuelGil** [comment]
This feature has been removed and will be used another project
